name: p1-cosign-version

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  cosign-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: v3.1.3
      - run: cosign version
